"""Receipt lineage supplement; no scientific array reads or execution."""
from pathlib import Path
import json,hashlib
H=Path(__file__).resolve().parent
P=H.parents[1]/'model_proposal/kl_bound_study/portable_plan'
pins={}
def load(p,h=None):
 b=p.read_bytes();v=hashlib.sha256(b).hexdigest()
 if h:assert v==h,str(p)
 pins[str(p)]=v
 return json.loads(b) if p.suffix=='.json' else b
r=load(P/'ROOT_EXTRACTION_RECEIPT.json','6c5b51073a0009ff93486e4c81403dd9aabc2bc241db508c73cbaafe1b1e4d38')
a=load(P/'ROOT_EXTRACTION_APPROVAL.json',r['approval_sha256'])
load(P/'root_safe_extract.py',r['orchestrator_sha256']);load(P/'integrity.py',a['integrity_sha256'])
attempt=load(P/'ROOT_EXTRACTION_ATTEMPT.json')
assert all(r[k]==v for k,v in attempt.items())
for k in ['archive_sha256','manifest_sha256']:assert r[k]==a[k]
assert r['scientific_members_parsed'] is False and a['authorized_phases']==['safe_extraction_only']
e=load(P/'ROOT_EXPORT_APPROVAL.json','5742ece95accd710c2ab853147855e16527942ad3410b941fd237ecc8dc3bcbf')
attempt=load(P/'kl_harm_private_v1.zip.attempt.json')
assert attempt['approval_sha256']==pins[str(P/'ROOT_EXPORT_APPROVAL.json')]
assert attempt['registry_sha256']==e['registry_sha256']
load(P/'build_replay.py',attempt['builder_sha256'])
z=load(P/'kl_harm_private_v1.zip.receipt.json')
for k in ['archive_sha256','manifest_sha256']:assert z[k]==r[k]
qa=load(H/'AUDIT.json')
for p,h in qa['source_output_pins'].items():load(Path(p),h)
load(H/'audit.py');load(H/'FIRST_AUDIT_ATTEMPT.md')
extras=sorted(str(p.relative_to(P/'fresh_extraction_v1')) for p in (P/'fresh_extraction_v1').rglob('*') if p.is_file() and '__pycache__' in p.parts)
with (H/'RECEIPT_BINDINGS.json').open('x') as f:json.dump({'status':'PASS','pins':pins,'post_replay_bytecode_files_not_original_payload':extras},f,indent=2)
print('PASS receipt lineage; generated bytecode extras',len(extras))
